#!/bin/bash

#
# This script initializes the venv for the ansible to work with linode
# 
export PATH="${HOME}/.local/bin:${PATH}"
uv venv
source .venv/bin/activate && uv pip install ansible linode_api4

